### ISSUE TITLE
Can windows works?

### ISSUE THREAD

**Issue by xichaoqiang** [darcamo/gdb_armadillo_helpers#5]
The package is very interested. Can windows10 works?

**Comment by darcamo** [comment]
I don't have windows and thus any change to the recipe to (explicitly) make it work with windows 10 needs to be done by someone else. I'll accept pull requests if they don't break anything.

Having said that, armadillo itself is very simple to install and can even be used as a header-only library, which is how this recipe installs it. The difficulty is correctly installing its dependencies, which are openblas and HDF5.

I also have recipes for openblas and HDF5, but my intention is to eventually use the recipes in conan-center instead of my own. If these two recipes from conan-center work with windows (I have no idea) then this armadillo recipe should work as well (maybe with minor changes). However, using openblas from conan-center currently is not working and I haven't had much time to investigate this.

**Comment by xichaoqiang** [comment]
Thanks for your reply.

**Comment by bkaangorur** [comment]
@xichaoqiang I use it in Windows 10 with Msys2. It works without any problem. And I did not change anything in helpers. Instead I only configured my gdbinit files.
